### ISSUE TITLE
Review our current security status and create a todo list of issues (high priority only for now on our accounts)

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1090]
## User Story

As a platform
We need confidence that we are secure
So that applications and data on the platform are safe

We need to have a focus on security and work out what we aren't doing that we should be doing.

https://security-guidance.service.justice.gov.uk/#operations-security

## Value

Once we understand our current issues we can work towards resolving them.

## Definition of done

- [ ] list of issues created
- [ ] engagement with MoJ security team
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by adeweetman-al** [comment]
Some recommendations based on some investigation into the mod platform accounts, categorised by type:

**MFA related**
https://security-guidance.service.justice.gov.uk/baseline-aws-accounts/#identity-and-access-management
Things to bear in mind:
- Things that only a root user can do: https://docs.aws.amazon.com/general/latest/gr/root-vs-iam.html#aws_tasks-that-require-root 
- Recommendation from AWS ControlTower: https://docs.aws.amazon.com/controltower/latest/userguide/strongly-recommended-guardrails.html 

To do:
- Prevent access to root accounts: https://github.com/ministryofjustice/modernisation-platform/issues/1149
- Set security hub findings to resolved
- Communicate MFA exemption to security team?

**MS key related**
Example control: KMS.3 AWS KMS keys should not be deleted unintentionally
This control flags up keys that are scheduled for deletion and will disappear after scheduled deletion period has expired.
To do:
- No action needed to solve - suggest not to suppress findings

**Default security group related**
Example control: 4.3 Ensure the default security group of every VPC restricts all traffic
https://security-guidance.service.justice.gov.uk/baseline-aws-accounts/#world-access 
Rules in default security groups (for default and non-default vpc) that would come into play if no security groups were specified when launching an EC2.
To do:
- If unused, bring any security groups in custom vpcs under terraform management and remove default rules
- If used, move any instances to custom security groups first and then perform the above

**Exposure-risk related**
Example control: S3.8 S3 Block Public Access setting should be enabled at the bucket-level
https://security-guidance.service.justice.gov.uk/baseline-aws-accounts/#world-access 
Assumption: there aren’t any long-lived EC2 instances in the mod platform
To do:
- Reconfigure/delete unused buckets in any mod platform bucket
- Remove/reconfigure security groups in dev/sandbox accounts allowing mgmt ports
- Remove/reconfigure instances with public IPs
- Reconfigure/remove instances not using IMDSv2
    - Create SCP to force usage of IMDSv2
- Suppress finding for ACM PCA bucket - believe public access required for this?
- Suppress finding regarding buckets allowing access from other accounts (e.g. Athena query buckets)
- Publish or re-share any guidance / good practise regarding publicly accessible resources (e.g. instances, buckets)

**Comment by adeweetman-al** [comment]
Future work identified so closing this.
