### ISSUE TITLE
Guidance/checklist for apps before they go into production

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1715]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Done - https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/production-ready-checklist.html
