### ISSUE TITLE
Spike: Scalability - member information 

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6317]
### User Story

As the modernisation product manager I need to have information about what is running on the modernisation platform. This enables us to respond in a timely manner to questions we get - eg what account do these IP relate to - but also so we know which members might be impacted by issues.
This ticket is to look at the best way of doing this, including what information we need to capture - eg which environment (eg prod or non-prod) contact details, accounts, etc

Time boxed spike - 3 days

### Value / Purpose

We can respond quickly to questions about the modernisation platform

### Definition of Done

- [x] Proposal for what we need to collect with some ideas about how we can do it
- [x] Approach agreed with the team
- [ ] Tickets raised to address

**Comment by dms1981** [comment]
For public IP addresses we can get these via the MOJ AWS `organisation-security` account through VPC IPAM (https://eu-west-2.console.aws.amazon.com/ipam/home?region=eu-west-2#PublicIpInsights).

For private IP addresses we would need to create and associate the relevant address pools in IPAM.

**Comment by richgreen-moj** [comment]
Here's a google doc in work in progress https://docs.google.com/document/d/14-9dTdGSsiN_lPXsQ52lnpZC3JiXqqpYG7Uv6477tMM/edit

**Comment by richgreen-moj** [comment]
I presented this to the team today (6/8/24) - next steps are @SimonPPledger will review the info provided and suggest which actions to take forward as a priority. Any follow-up stories can be drafted as a result of this.

**Comment by mikereiddigital** [comment]
We discussed the outcomes of this spike and I'm happy that it's been completed.
