### ISSUE TITLE
[SPIKE] NCSC - AWS Organizations and Service Control Policies 

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6728]
### User Story

Following on from NCSC's review"
**AWS Organizations and Service Control Policies**
AWS accounts for the Modernisation Platform sit within the MoJ’s AWS Organization hierarchy. Due to this, Modernisation Platform accounts inherit Service Control Policies and permissions from accounts above them in the Organization hierarchy. These accounts are managed by another team within MoJ, therefore there is a reliance on the security posture of this team to ensure that no undue risk is presented to the Modernisation Platform.

**Risk**: A compromise of a root account or account above the Modernisation Platform in the AWS Organization Hierarchy could lead to a compromise of the Modernisation Platform. 

**NCSC's Recommendation:** Ensure that the accounts above the Modernisation Platform in the AWS Organization hierarchy are appropriately managed and secured. 

MoJ Response: We could configure to use a desktop server (eg azure) - but what would happen if there was a MoJ wide network issue? Is it better to cover procedurally - eg we log when accessed, or ensure changes are done by 2 people 

This ticket is to look at feasibility of creating implementing access via a secure server, including drawbacks.

### Value / Purpose

Provide a more secure platform

### Useful Contacts

Jon Lawrence - we should review our options with him, as the Chief Information Security Officer for MoJ

### Proposal / Unknowns

Is this out of our hands as a platform team?

If AWS Organizational Unit SCPs are a potential thread due to inheritance, what can we do to reduce the risk of inherited SCP policies?

### Definition of Done

- [ ] Spike appropriately timeboxed
- [ ] Can we do something with SCPs defined in the OU for the Modernisation Platform
- [ ] Possible option to reduce this risk, including any negative impact to the service we provide
- [ ] Agreement on whether to action
- [ ] If required, ticket raised to implement

**Comment by SimonPPledger** [comment]
We have agreed, for now, that we are not going to do this
