### ISSUE TITLE
Notification/alerting system in Modernisation Platform

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#6817]
### User Story

As a Modernisation Platform member user
I want to be notified about health of resources or upcoming events that need actioning (e.g. expiring certificates)
So that I can react and fix/prevent an issue.

### Value / Purpose

Healthy application/system means no outages.

### Additional Information

This want came as an [ask channel request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1712759084568309) and it is to look if we can implement a new one or reuse our existing alerting system that can be easily consumed by the members. 

Currently MP alerting workflow is made of: CloudWatch -> SNS -> PagerDuty -> Slack and using this solution is documented [here](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/integrating-alarms-with-pagerduty-with-slack.html#integrating-cloudwatch-alarms-with-pagerduty-and-slack).

This ticket is to remove the need of PagerDuty acting as a mid-man and to integrate with a variety of resources (CloudWatch, EventBridge, SNS) rather than being limited to one only (although it could start with one and then build on it).

The user that requested this, suggested EventBridge → SNS → e-mail → Slack as an approach described in [here](https://medium.com/@varunarora2201/stay-ahead-of-expiring-certificates-using-acm-api-and-amazon-eventbridge-with-terraform-code-60a03eda1108), which could be considered.

### Definition of Done

- [x] New alerting system is implemented (ideally as a module) and it does not use PagerDuty
- [x] If applicable, tests are implemented
- [x] User docs have been updated
- [x] Another team member has reviewed
- [x] Pipeline runs green

**Comment by dms1981** [comment]
Is this potentially too broad? Is this ticket meant to cover the creation of a new alerting/notification module that we can use, or a one-off to cover alerting when certificates are reaching their expiration date that could later be extended to replace PagerDuty as a middleman?

**Comment by dms1981** [comment]
As you noted in Slack, @ewastempel , maybe this is a better fit for enrolling with Observability Platform and getting the information through there?

**Comment by richgreen-moj** [comment]
🤔 For this ticket I'm thinking of creating a generic module (perhaps called `modernisation-platform-aws-health-events`) that creates an eventbridge rule that monitors aws health events , posts these to an SNS topic which can then either be hooked in to by email or perhaps even Slack with AWS ChatBot - as described [here](https://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html)

This would capture the needs of the user as certificate renewals are posted as [health events ](https://docs.aws.amazon.com/acm/latest/userguide/check-certificate-renewal-status.html#check-renewal-status-phd) but would also serve as a more generic tool for users to configure alerts for other important health events.

If possible perhaps the module could be configurable to point at particular services rather than all. We'll see

**Comment by ewastempel** [comment]
Further to my previous comment, if the 1st is not achievable, the 2nd shouldn't be implemented. However it is still worth doing 1st, even if the 2nd cannot be achieved.

**Comment by richgreen-moj** [comment]
So current process is...
1. Create SNS topic
2. Create Alarm (which notifies topic)
3. Integrate to PagerDuty (fun and games)

If we the aim is to bypass PD then we could use AWS ChatBot and I could use [this TF resource](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/chatbot_slack_channel_configuration) in a module that can be called where you can provide a list of existing topics etc that you want to get notified on via Slack.

I think there would be a manual element to setting up a chatbot slack client per account but once that's done you can do the rest in code.

**Comment by richgreen-moj** [comment]
This PR https://github.com/ministryofjustice/modernisation-platform-terraform-aws-chatbot/pull/1 provides the detail on the new [AWS Chatbot module](https://github.com/ministryofjustice/modernisation-platform-terraform-aws-chatbot) that has been created for AWS Chatbot which I have tested out in Sprinkler as well as writing some unit tests for the module.
