### ISSUE TITLE
NCSC: Rationalise ModP engineering and admin accounts to ensure more functionality provided by engineering account

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7436]
### User Story

**Following on from the NCSC review:**
AWS accounts hosting the Modernisation Platform are accessed using standard issue MoJ devices. The security posture of these devices was not discussed, however, if these devices render untrusted content through on-device internet browsing or email access, they could be at a higher risk of compromise. Due to this, using a standard issue MoJ device for Administrators and Developers could present an undue risk to the Modernisation Platform and the services it hosts.

**Risk**: An attacker could gain unauthorised access to code and production environments in the event that an MoJ device accessing these environments is compromised. This could lead to loss or modification of sensitive data and/or unauthorised access to services hosted in the Modernisation Platform.
Recommendation: Ensure all configuration changes to the Modernisation Platform are performed in code rather than manually in the console. 

**This ticket is to change the Mod Platform engineer role to allow some of the less risky 'admin' changes (ie so that these have to be done via code)**

### Value / Purpose

This reduces the risk outlined by NCSC

### Additional Information

n/a

### Definition of Done

- [x] Compare permissions between Engineering and Admin, and create a list from this.
- [x] Discuss list after standup / short meeting about what can be moved to engineering role.
- [x] Agreed list of functions that can move from admin account to modP engineering account
- [x] Accounts changed accordingly

**Comment by Kudzai-moj** [comment]
Did not use the Admin role for this ticket because its impossible to expand its json policy and see full list of permissions, the most i could do was to compare missing services.

Ended up using the document below, and from it added the additional policies as below,

specific create, update and delete permissions to the Modernisation Platform Engineering role which was previously read only. The role has the permissions,

- Developer Additional Statements
- Instance Management
- Reporting Operations
- Fleet Manager
- Common Statements - Deny is now Allow

https://docs.google.com/document/d/1vYCAtQpHgBBSMXgs7--uTwV7idt3cI3HRTZ1kKrZMCQ/edit#heading=h.qokru6g8dphp

**Comment by Kudzai-moj** [comment]
can be closed with caveat - This is OK for now, but the management location of the MP engineering roles will be revisited in the future, when the MP team takes over the management of the SSO roles/permission set for the whole org.

 https://github.com/ministryofjustice/aws-root-account/pull/959

**Comment by mikereiddigital** [comment]
This looks good to me. Happy to move it to done.
